const BASE_CLASSES = [
  "Meow",
  "Bark",
  "Cat",
  "Dog",
  "Domestic_animals_and_pets",
  "Fowl",
  "Livestock_and_farm_animals_and_working_animals",
  "Crow",
  "Bird_vocalization_and_bird_call_and_bird_song",
  "Bird",
  "Animal",
  "Cowbell",
  "Church_bell",
  "Bicycle_bell",
  "Chime",
  "Bell",
  "Brass_instrument",
  "Keyboard_(musical)",
  "Drum",
  "Gong",
  "Drum_kit",
  "Percussion",
  "Electric_guitar",
  "Bass_guitar",
  "Guitar",
  "Plucked_string_instrument",
  "Harmonica",
  "Musical_instrument",
  "Music",
  "Thunder",
  "Stream",
  "Rain",
  "Pour",
  "Water",
  "Vehicle_horn_and_car_horn_and_honking",
  "Ringtone",
  "Alarm",
  "Knock",
  "Typing",
  "Writing",
  "Motorcycle",
  "Engine",
  "Explosion"
];

const NOVEL_CLASSES = [
  "Chicken_and_rooster",
  "Chirp_and_tweet",
  "Trumpet",
  "Piano",
  "Acoustic_guitar",
  "Computer_keyboard",
  "Accelerating_and_revving_and_vroom",
  "Gunshot_and_gunfire"
];

const AUDIO_SLOTS = [
  { label: "Base example 01", file: "base-example-01.wav", enabled: false },
  { label: "Base example 02", file: "base-example-02.wav", enabled: false },
  { label: "Novel example 01", file: "novel-example-01.wav", enabled: false },
  { label: "Novel example 02", file: "novel-example-02.wav", enabled: false },
  { label: "Novel example 03", file: "novel-example-03.wav", enabled: false },
  { label: "Novel example 04", file: "novel-example-04.wav", enabled: false }
];
